// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("authors")
export class authorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
name: string;

@Column("date",{nullable: true})
dateOfBirth: Date;

@Column("text",{nullable: true})
nationality: string;

@Column("integer",{nullable: true})
listOfBooks: number;


}
