//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Customers")
export class CustomersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
customerId: string;

@Column({nullable: true})
email: string;

@Column({nullable: true})
password: string;

@Column({nullable: true})
name: string;

@Column({nullable: true})
age: number;

@Column({nullable: true})
gender: string;

@Column({nullable: true})
weight: number;

@Column({nullable: true})
height: number;

@Column({nullable: true})
healthConditions: string;

@Column({nullable: true})
goals: string;

@Column({nullable: true})
dietaryPreferences: string;

@Column({nullable: true})
billingAddress: string;

@Column({nullable: true})
country: string;

@Column({nullable: true})
phone: string;


}
