// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Goals")
export class GoalsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
goalDescription: string;

@Column("real",{nullable: true})
baselineMetric: number;

@Column("real",{nullable: true})
targetMetric: number;

@Column("date",{nullable: true})
deadline: Date;

@Column("real",{nullable: true})
currentProgress: number;


}
