//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("HealthMetrics")
export class HealthMetricsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
metricId: string;

@Column({nullable: true})
customerId: number;

@Column({nullable: true})
type: string;

@Column({nullable: true})
value: number;

@Column({nullable: true})
unit: string;

@Column({nullable: true})
date: Date;


}
