//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Inventory")
export class InventoryEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("integer",{nullable: true})
userId: number;

@Column("integer",{nullable: true})
cardId: number;

@Column("date",{nullable: true})
recordedDate: Date;


}
