//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Nutrition")
export class NutritionEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
mealId: string;

@Column({nullable: true})
customerId: number;

@Column({nullable: true})
foodItem: string;

@Column({nullable: true})
quantity: number;

@Column({nullable: true})
calories: number;

@Column({nullable: true})
macronutrients: string;

@Column({nullable: true})
date: Date;


}
