//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("OrderDetails")
export class OrderDetailsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("integer",{nullable: true})
orderId: number;

@Column("integer",{nullable: true})
productId: number;

@Column("real",{nullable: true})
price: number;

@Column("integer",{nullable: true})
quantity: number;


}
