//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("ProductCategories")
export class ProductCategoriesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("integer",{nullable: true})
categoryId: number;

@Column("integer",{nullable: true})
productId: number;

@Column("text",{nullable: true})
description: string;


}
