//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Sets")
export class SetsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("integer",{nullable: true})
setId: number;

@Column("text",{nullable: true})
setName: string;

@Column("date",{nullable: true})
releaseDate: Date;

@Column("integer",{nullable: true})
totalCards: number;


}
