//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("SupportTickets")
export class SupportTicketsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
ticketId: string;

@Column({nullable: true})
userId: number;

@Column({nullable: true})
customerId: number;

@Column({nullable: true})
description: string;

@Column({nullable: true})
status: string;

@Column({nullable: true})
creationDate: Date;

@Column({nullable: true})
resolutionDate: Date;

@Column({nullable: true})
serialNo: number;


}
