// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Suppliers")
export class SuppliersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
supplierName: string;

@Column("text",{nullable: true})
productService: string;

@Column("real",{nullable: true})
sustainabilityRating: number;

@Column("text",{nullable: true})
certifications: string;


}
