// Source code generated by AppGPT (www.appgpt.tech)

 import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput
} from "react-admin";
import { useRecordContext } from "react-admin";
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {

  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword =  '********';

  return (
      <span>{maskedPassword}</span>
  );
};
const ListActions = () => (
    <TopToolbar>
        <FilterButton />
        <CreateButton />
        <ExportButton />
        <SelectColumnsButton />
    </TopToolbar>
);
const membersTitle = () => {
  const record = useRecordContext();
  return <span>members {record ? `"${ record.name }"` : ""}</span>;
};

export const membersList = () => (
      <List actions={<ListActions  />} filters={ResourceFilters} >
        <DatagridConfigurable>
          <TextField source="memberID" />
<TextField source="name" />
<EmailField source="emailAddress" />
<TextField source="phoneNumber" />
<TextField source="address" />
<DateField source="membershipStartDate" /><EditButton />

        </DatagridConfigurable>
      </List>
      );

export const membersEdit = () => (
                    <Edit title={<membersTitle />}>
                      <SimpleForm>
                        <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
                          <Grid item xs={4}>
<TextInput source="memberID"   /></Grid>
<Grid item xs={4}>
<TextInput source="name"   /></Grid>
<Grid item xs={4}>
<TextInput source="emailAddress"   /></Grid>
<Grid item xs={4}>
<TextInput source="phoneNumber"   /></Grid>
<Grid item xs={4}>
<TextInput source="address"   /></Grid>
<Grid item xs={4}>
<DateInput source="membershipStartDate"   /></Grid>
                        </Grid>
                      </SimpleForm>
                    </Edit>
                  );

export const membersCreate = () => (
                                  <Create>
                                    <SimpleForm>
                                      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
                                        <Grid item xs={4}>
<TextInput source="memberID"   /></Grid>
<Grid item xs={4}>
<TextInput source="name"   /></Grid>
<Grid item xs={4}>
<TextInput source="emailAddress"   /></Grid>
<Grid item xs={4}>
<TextInput source="phoneNumber"   /></Grid>
<Grid item xs={4}>
<TextInput source="address"   /></Grid>
<Grid item xs={4}>
<DateInput source="membershipStartDate"   /></Grid>
                                      </Grid>
                                    </SimpleForm>
                                  </Create>
                                );

const ResourceFilters = [
      <TextInput source="q" label="Search" alwaysOn />,
,
,
,
,
,
,

    ];


