// Source code generated by AppGPT (www.appgpt.tech)

 import { Card, CardContent, CardHeader } from "@mui/material";
    export const Dashboard = () => (
      <Card>
      <CardHeader title="EcoPulse" />
      <CardContent> 
      It is an app empowering your green journey with real-time sustainability tracking, eco-challenges, and personalized tips to reduce your carbon footprint.
      <p>Built with{' '}
      <a
        href="https://www.appgpt.tech"
        target="_blank"
        rel="noopener noreferrer"
      >
        AppGPT
      </a></p>
      </CardContent>

      </Card>
    );