// Source code generated by AppGPT (www.appgpt.tech)

 // in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"books":{"name":"Books","fields":{"title":"Title","author":"Author","ISBN":"Isbn","publicationDate":"Publication Date","genre":"Genre","status":"Status","id":"id"}},"authors":{"name":"Authors","fields":{"name":"Name","dateOfBirth":"Date Of Birth","nationality":"Nationality","listOfBooks":"List Of Books","id":"id"}},"members":{"name":"Members","fields":{"memberID":"Member Id","name":"Name","emailAddress":"Email Address","phoneNumber":"Phone Number","address":"Address","membershipStartDate":"Membership Start Date","id":"id"}},"loans":{"name":"Loans","fields":{"loanID":"Loan Id","bookID":"Book Id","memberID":"Member Id","loanDate":"Loan Date","dueDate":"Due Date","returnDate":"Return Date","id":"id"}}}};
const frResources = { resources: {"books":{"name":"Books (fr)","fields":{"title":"Title (fr)","author":"Author (fr)","ISBN":"Isbn (fr)","publicationDate":"Publication Date (fr)","genre":"Genre (fr)","status":"Status (fr)","id":"id"}},"authors":{"name":"Authors (fr)","fields":{"name":"Name (fr)","dateOfBirth":"Date Of Birth (fr)","nationality":"Nationality (fr)","listOfBooks":"List Of Books (fr)","id":"id"}},"members":{"name":"Members (fr)","fields":{"memberID":"Member Id (fr)","name":"Name (fr)","emailAddress":"Email Address (fr)","phoneNumber":"Phone Number (fr)","address":"Address (fr)","membershipStartDate":"Membership Start Date (fr)","id":"id"}},"loans":{"name":"Loans (fr)","fields":{"loanID":"Loan Id (fr)","bookID":"Book Id (fr)","memberID":"Member Id (fr)","loanDate":"Loan Date (fr)","dueDate":"Due Date (fr)","returnDate":"Return Date (fr)","id":"id"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    