// Source code generated by AppGPT (www.appgpt.tech)

 // in i18nProvider.js
    import { mergeTranslations } from "ra-core";
    import polyglotI18nProvider from "ra-i18n-polyglot";
    import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

    const enResources = { resources: {"Users":{"name":"Users","fields":{"userId":"User Id","email":"Email","name":"Name","id":"id"}},"EmissionSources":{"name":"Emission Sources","fields":{"sourceType":"Source Type","quantityUsed":"Quantity Used","emissionFactors":"Emission Factors","totalEmissions":"Total Emissions","id":"id"}},"ResourceUsage":{"name":"Resource Usage","fields":{"resourceType":"Resource Type","quantityConsumed":"Quantity Consumed","measurementUnit":"Measurement Unit","periodOfConsumption":"Period Of Consumption","id":"id"}},"Goals":{"name":"Goals","fields":{"goalDescription":"Goal Description","baselineMetric":"Baseline Metric","targetMetric":"Target Metric","deadline":"Deadline","currentProgress":"Current Progress","id":"id"}},"WasteManagement":{"name":"Waste Management","fields":{"wasteType":"Waste Type","quantityGenerated":"Quantity Generated","recyclingMethod":"Recycling Method","reductionInitiatives":"Reduction Initiatives","id":"id"}},"Suppliers":{"name":"Suppliers","fields":{"supplierName":"Supplier Name","productService":"Product Service","sustainabilityRating":"Sustainability Rating","certifications":"Certifications","id":"id"}},"Products":{"name":"Products","fields":{"name":"Name","id":"id"}},"Employees":{"name":"Employees","fields":{"id":"Id","mail":"Mail"}},"Reports":{"name":"Reports","fields":{"description":"Description","id":"id"}}}};
const frResources = { resources: {"Users":{"name":"Users (fr)","fields":{"userId":"User Id (fr)","email":"Email (fr)","name":"Name (fr)","id":"id"}},"EmissionSources":{"name":"Emission Sources (fr)","fields":{"sourceType":"Source Type (fr)","quantityUsed":"Quantity Used (fr)","emissionFactors":"Emission Factors (fr)","totalEmissions":"Total Emissions (fr)","id":"id"}},"ResourceUsage":{"name":"Resource Usage (fr)","fields":{"resourceType":"Resource Type (fr)","quantityConsumed":"Quantity Consumed (fr)","measurementUnit":"Measurement Unit (fr)","periodOfConsumption":"Period Of Consumption (fr)","id":"id"}},"Goals":{"name":"Goals (fr)","fields":{"goalDescription":"Goal Description (fr)","baselineMetric":"Baseline Metric (fr)","targetMetric":"Target Metric (fr)","deadline":"Deadline (fr)","currentProgress":"Current Progress (fr)","id":"id"}},"WasteManagement":{"name":"Waste Management (fr)","fields":{"wasteType":"Waste Type (fr)","quantityGenerated":"Quantity Generated (fr)","recyclingMethod":"Recycling Method (fr)","reductionInitiatives":"Reduction Initiatives (fr)","id":"id"}},"Suppliers":{"name":"Suppliers (fr)","fields":{"supplierName":"Supplier Name (fr)","productService":"Product Service (fr)","sustainabilityRating":"Sustainability Rating (fr)","certifications":"Certifications (fr)","id":"id"}},"Products":{"name":"Products (fr)","fields":{"name":"Name (fr)","id":"id"}},"Employees":{"name":"Employees (fr)","fields":{"id":"Id (fr)","mail":"Mail (fr)"}},"Reports":{"name":"Reports (fr)","fields":{"description":"Description (fr)","id":"id"}}}};


    const en = mergeTranslations(enOriginal,enResources);
const fr = mergeTranslations(frOriginal,frResources);

    const translations = { en, fr};
    export const i18nProvider = polyglotI18nProvider(
      (locale) => translations[locale],
      "en", //default locale
      [{"locale":"en","name":"English"},{"locale":"fr","name":"Français"}]
    );
    